name: 'ACR Cleanup'

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight UTC
  workflow_dispatch:  # Allow manual trigger

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

permissions:
  contents: read
  id-token: write

jobs:
  cleanup:
    name: 'Cleanup Old Images'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Purge old images'
      run: |
        # Keep only the latest 5 images, delete everything else
        az acr run \
          --registry ${{ secrets.REGISTRY_NAME }} \
          --cmd "acr purge --filter 'weather-app:.*' --keep 5 --ago 30d" /dev/null
