name: Clean up ACR

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  workflow_dispatch:

env:
  REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
  IMAGE_NAME: remix-weather-app

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Clean up old images
        run: |
          # Keep the latest 5 images and images newer than 30 days
          az acr run \
            --registry ${{ env.REGISTRY_NAME }} \
            --cmd "acr purge --filter '${{ env.IMAGE_NAME }}:.*' --ago 30d --keep 5 --untagged" \
            /dev/null
