name: Build and Push Container

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/container-build.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/container-build.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: remix-weather-app
  REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR
        run: |
          az acr build \
            --registry ${{ env.REGISTRY_NAME }} \
            --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --image ${{ env.IMAGE_NAME }}:latest \
            .

      - name: Update Kubernetes manifests
        if: github.event_name != 'pull_request'
        run: |
          # Replace the image tag in the deployment manifest
          sed -i "s|image:.*|image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s/deployment.yaml
          
          # Commit and push the changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
