name: 'Container Build and Push'

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/container-*.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/container-*.yml'
      - 'Dockerfile'

permissions:
  contents: read
  id-token: write

env:
  REGISTRY: ${{ secrets.REGISTRY_NAME }}.azurecr.io
  IMAGE_NAME: weather-app

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Build and push image'
      run: |
        az acr build --registry ${{ secrets.REGISTRY_NAME }} \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --image ${{ env.IMAGE_NAME }}:latest \
          ./src
