name: 'Docker Build'

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'ACR login'
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: 'Build and push image'
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/weather-app:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/weather-app:${{ github.sha }}
