name: Terraform Static Analysis

on:
  push:
    branches:
      - '**'
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-static-analysis.yml'

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./infra

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Run TFLint
        run: tflint --recursive
        working-directory: ./infra
