name: 'Terraform Static Analysis'

on:
  push:
    branches:
      - '*'
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-*.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  static-analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      working-directory: ./infra

    - name: Terraform Init
      id: init
      run: terraform init -backend=false
      working-directory: ./infra

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./infra

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: ./infra
